#!/bin/sh
#
# "Moddable SDK / ESP32" install shell script for Linux
#
# Set the sudo-password from ./passwd.sudo file
echo "\n*** Check sudo-password"
#
INSTLR_PATH=$(cd $(dirname $0); pwd)
PASSWD_FILE=$INSTLR_PATH/passwd.sudo
if [ -e $PASSWD_FILE ]; then
   SUDO_PASSWD=$(cat $PASSWD_FILE)
   echo $SUDO_PASSWD| sudo -S ls ./ 1> /dev/null
   if [ $? -gt 0 ]; then
     echo "\n*** ERROR! check your 'passwd.sudo' file\n"
     exit 1
   else
     echo " confirmed"
   fi
else
#   SUDO_PASSWD=""
   echo "\n*** 'passwd.sudo' file is none"
   echo "\nInput password manualy when it is required"
   echo "\n- Hit ENTER-key to continue -"; read
fi
#
# Set the filename of environment variables setting file for Moddable-SDK
MODDABLE_PROFILE=~/.moddable_profile
#
if [ -e $MODDABLE_PROFILE ]; then
    cp -f $MODDABLE_PROFILE  $MODDABLE_PROFILE.org
fi
echo "\# $(date) " > $MODDABLE_PROFILE
#
# Set the filename of initial execution when terminal started.
EXECUTE_PROFILE=~/.bashrc
#
# Backup $EXECUTE_PROFILE to $EXECUTE_PROFILE.org
cp -f $EXECUTE_PROFILE $EXECUTE_PROFILE.org
# Append command of $MODDABLE_PROFILE execution to tail of $EXECUTE_PROFILE
echo "source $MODDABLE_PROFILE" >> $EXECUTE_PROFILE
#
# Set the using serialport. default:/dev/cu.SLAB_USBtoUART。
SERIAL_DEV=/dev/ttyUSB0
#
echo "export UPLOAD_PORT=$SERIAL_DEV" >> $MODDABLE_PROFILE
#
##############################
# SDK Host environmet set up #
#############################
#
echo "\n*** Installer start Moddable-SDK ***"
#
# Required tools etc. for build SDK host
FILE1="libgtk-3-dev"
FILE2="gcc git wget make libncurses-dev flex bison gperf python python-pip python-setuptools python-serial"
# apt-get tools etc.
if [ -z $SUDO_PASSWD ]; then
  echo "*** Keyin sudo-password"
  sudo apt-get install $FILE1
  sudo apt-get install $FILE2
else
  echo $SUDO_PASSWD | sudo -S apt-get install $FILE1 -y
  echo $SUDO_PASSWD | sudo -S apt-get install $FILE2 -y
fi
#
echo "\n*** Create ~/Projects folder"
cd ~
mkdir Projects
#
echo "\n*** Download the Moddable repository from github\n"
cd ./Projects
git clone https://github.com/Moddable-OpenSource/moddable
#
echo "\n*** Setup the MODDABLE environment variables"
echo "export MODDABLE=\$HOME/Projects/moddable" >> $MODDABLE_PROFILE
echo "export PATH=\$MODDABLE/build/bin/lin/release:\$PATH" >> $MODDABLE_PROFILE
export MODDABLE=$HOME/Projects/moddable
export PATH=$MODDABLE/build/bin/lin/release:$PATH
#
echo "\n*** Build the Moddable tools\n"
cd $MODDABLE/build/makefiles/lin
make
#
echo "\n*** Install the Moddable tools\n"
make install
#
################
# ESP32 Set up #
################
#
echo "\n*** Create ~/esp32 folder"
cd ~
mkdir ~/esp32
#
echo "\n*** Download and untar the ESP32 GCC toolchain\n"
cd ~/esp32
wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz -O - | tar zx
#
echo "\n*** Clone the ESP-IDF repository from github\n"
git clone --recursive https://github.com/espressif/esp-idf.git
#
echo "\n*** Use the 3.1 version\n"
cd esp-idf
git checkout release/v3.1
git submodule update
#
echo "\n*** Set the IDF_PATH environment variable"
echo "export IDF_PATH=\$HOME/esp32/esp-idf" >>  $MODDABLE_PROFILE
export IDF_PATH=$HOME/esp32/esp-idf
#
echo "\n*** Install the required Python packages\n"
cd ~/esp32
#
FILE1="esptool"
if [ -z $SUDO_PASSWD ]; then
  echo "*** Keyin sudo-password"
  sudo pip install $FILE1
else
  echo $SUDO_PASSWD | sudo -S pip install $FILE1
fi
#
python -m pip install --user -r $IDF_PATH/docs/requirements.txt
#
echo "\n*** Set the IDF_PATH environment variable"
echo "export PATH=\$PATH:\$HOME/esp32/xtensa-esp32-elf/bin" >>  $MODDABLE_PROFILE
export PATH=$PATH:$HOME/esp32/xtensa-esp32-elf/bin
#
echo "\n*** Finished!!! ***\n"
