#!/bin/sh
#
# "Moddable SDK" install shell script for macOS
#
#### pre settings ####
#
# Set the sudo password to ./passwd.sudo file
INSTLR_PATH=$(cd $(dirname $0); pwd)
PASSWD_FILE=$INSTLR_PATH/passwd.sudo
#
# Set the filename of environment variables setting file for Moddable-SDK
MODDABLE_PROFILE=~/.moddable_profile
touch $MODDABLE_PROFILE
#
# Set the filename of initial execution when terminal started.
EXECUTE_PROFILE=~/.bash_profile
#
# Set the using serialport. default:/dev/cu.SLAB_USBtoUART
SERIAL_DEV=/dev/cu.SLAB_USBtoUART
#
echo "export UPLOAD_PORT=$SERIAL_DEV" > $MODDABLE_PROFILE
#
##########################
# Host environmet set up #
##########################
#
echo '\n*** Installer start "Moddable-SDK_Host for mac" ***'
echo '\n*** Create ~/Projects folder'
cd ~
mkdir Projects
#
echo "\n*** Download the Moddable repository from github\n"
cd ./Projects
git clone https://github.com/Moddable-OpenSource/moddable
#
echo "\n*** Setup the MODDABLE environment variables"
echo 'export MODDABLE="$HOME/Projects/moddable"' >> $MODDABLE_PROFILE
echo 'export PATH="$MODDABLE/build/bin/mac/release:$PATH"' >> $MODDABLE_PROFILE
export MODDABLE="$HOME/Projects/moddable"
export PATH="$MODDABLE/build/bin/mac/release:$PATH"
#
echo "\n*** Setup the Xcode for making GUI Apps"
#
COMMAND='xcode-select -s /Applications/Xcode.app/Contents/Developer'
if [ -e $PASSWD_FILE ]; then
   SUDO_PASSWD=$(cat $PASSWD_FILE)
   echo $SUDO_PASSWD | sudo -S $COMMAND
else
   echo "*** Keyin sudo password"
   sudo $COMMAND
fi
echo "\n\n*** Build the Moddable tools\n"
cd $MODDABLE/build/makefiles/mac
make
#
# Backup $EXECUTE_PROFILE to $EXECUTE_PROFILE.org
cp -f $EXECUTE_PROFILE $EXECUTE_PROFILE.org
# Append command of $MODDABLE_PROFILE execution to tail of $EXECUTE_PROFILE
echo "source $MODDABLE_PROFILE" >> $EXECUTE_PROFILE
#
echo "\n\n*** Finished ***"
